# Generated by Django 5.1.4 on 2025-01-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_recurring_event_recurrence_interval_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Concert', 'Concert'), ('Wedding', 'Wedding'), ('Seminar', 'Seminar')], default='conference', max_length=50),
        ),
    ]
